import { METHOD_POST } from "@/actions/actionTypes";
import { apiClient } from "@/lib/apiClient";
import { useFetch } from "@/lib/useFetch";
import { emailServices } from "@/services/emailServices";
import { welcomeTemplate } from "@/templates/welcome";
import { Button } from "@/antd/lib/AntRegistry";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [state, setState] = useState([]);

  let { data, error, loading, refetch } = useFetch(`/api/users`);
  console.log(data, "datt_____");

  const handleDelete = async (id: string) => {
    debugger;
    try {
      let apiRes = await apiClient(`/api/users/${id}`, "DELETE");
      refetch();
    } catch (error) {}
  };
  const sendMail = async () => {
    const payload = {
      name:'Rishabh sharma',
      email:"hello@gmail.com",
      password:"12345@Qwerty"
    }
    try {
      const apiRes:any = await apiClient(`/api/users/signup`,METHOD_POST,payload)
      if(apiRes?.data){
        const response = await emailServices(payload.email,"Welcome to flipkart",welcomeTemplate)
      }
    } catch (error) {
      
    }
   
  };
 

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        homepage
        {Array.isArray(data) &&
          data.map((res: any, index: number) => (
            <div>
              <div>{res?.name}</div>
              <button onClick={() => handleDelete(res._id)}>Delete</button>
            </div>
          ))}
        <Button onClick={() => sendMail()}>Send mail</Button>
      </div>
    </>
  );
}
